on:
  issues:
    types: [assigned]

permissions:
  issues: write  # Grant write permissions to issues

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Post a GIF as a comment
        uses: actions/github-script@v4
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "![Alt Text](https://media.giphy.com/media/uurU31TE5YAUM/giphy.gif)"
            });
